### ISSUE TITLE
Issue importing mp4 file 

### ISSUE THREAD

**Issue by yeongnamtan** [RizwanMunawar/yolov8-object-tracking#14]
Previously, I had no issue doing inferences on  mp4 file. But somehow, when I tried to do inference now on my mp4 file, the programme gives me this error.   It works if I used some of my older mp4 files.

[2023-04-20 14:23:57,021][root.tracker][INFO] - Loading weights from deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done!
Ultralytics YOLOv8.0.3 🚀 Python-3.9.16 torch-1.13.1+cu117 CUDA:0 (Tesla T4, 15110MiB)
Fusing layers... 
Model summary: 268 layers, 68124531 parameters, 0 gradients, 257.4 GFLOPs
Error executing job with overrides: ['model=best_yolov8x_v8.0.0_11April2023.pt', 'conf=0.01', 'source=/root/Yolov5_DeepSort_Pytorch/VideosForTracking/P69_IMG_1095_0.1_Part1.mp4']
Traceback (most recent call last):
  File "/root/ultralytics-main/ultralytics/yolo/v8/detect/tracking_fish_counting.py", line 321, in predict
    predictor()
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/ultralytics-main/ultralytics/yolo/engine/predictor.py", line 189, in __call__
    s += self.write_results(i, preds, (p, im, im0s))
  File "/root/ultralytics-main/ultralytics/yolo/v8/detect/tracking_fish_counting.py", line 303, in write_results
    outputs = deepsort.update(xywhs, confss, oids, im0)
  File "/root/ultralytics-main/ultralytics/yolo/v8/detect/deep_sort_pytorch/deep_sort/deep_sort.py", line 29, in update
    features = self._get_features(bbox_xywh, ori_img)
  File "/root/ultralytics-main/ultralytics/yolo/v8/detect/deep_sort_pytorch/deep_sort/deep_sort.py", line 110, in _get_features
    features = self.extractor(im_crops)
  File "/root/ultralytics-main/ultralytics/yolo/v8/detect/deep_sort_pytorch/deep_sort/deep/feature_extractor.py", line 43, in __call__
    im_batch = self._preprocess(im_crops)
  File "/root/ultralytics-main/ultralytics/yolo/v8/detect/deep_sort_pytorch/deep_sort/deep/feature_extractor.py", line 38, in _preprocess
    im_batch = torch.cat([self.norm(_resize(im, self.size)).unsqueeze(
  File "/root/ultralytics-main/ultralytics/yolo/v8/detect/deep_sort_pytorch/deep_sort/deep/feature_extractor.py", line 38, in <listcomp>
    im_batch = torch.cat([self.norm(_resize(im, self.size)).unsqueeze(
  File "/root/ultralytics-main/ultralytics/yolo/v8/detect/deep_sort_pytorch/deep_sort/deep/feature_extractor.py", line 36, in _resize
    return cv2.resize(im.astype(np.float32)/255., size)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by RizwanMunawar** [comment]
@yeongnamtan! seems like your mp4 file is corrupted. This error is related to OpenCV, it's not the YOLOv8 error.
Apart from that, you can post this issue in the OpenCV-GitHub issues section

**Comment by yeongnamtan** [comment]
I tried several other MP4 and they have the same problem.

Interestingly, I tried on Yolov5 and there is no problem.

**Comment by yeongnamtan** [comment]
I can read the mp4 files using Ultralytics 8.0.20.

**Comment by yeongnamtan** [comment]
@RizwanMunawar/yolov8-object-tracking
***@***.***>  do you
now have support for latest package ?
