### ISSUE TITLE
    from sort import * ?     anyone know this problem?

### ISSUE THREAD

**Issue by Amos2008** [RizwanMunawar/yolov8-object-tracking#17]
Traceback (most recent call last):
  File "yolo\v8\detect\detect_and_trk.py", line 5, in <module>
    from sort import *
  File "E:\yolov8\gitobject\yolov8-object-tracking\yolo\v8\detect\sort.py", line 14, in <module>
    from filterpy.kalman import KalmanFilter
ModuleNotFoundError: No module named 'filterpy'

**Comment by stephenbradshaw82** [comment]
Did you ever find the solution to this?

**Comment by Ahmant** [comment]
Did you try `pip install filterpy`?
